import { WeightUnits } from "@/database/models/types/products.type";
import moment from "moment";

export const categoryData = [
  {
    category: "Rice",
  },
  {
    category: "Wheat",
  },
  {
    category: "Besan",
  },
  {
    category: "Maida",
  },
  {
    category: "Others",
  },
];

export const productsData = [
  {
    name: "Basmati Rice 5kg",
    brand: "India Gate",
    category_id: 1,
    SKU: "SKU001",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 580.0,
    available_quantity: 50,
    sold_quantity: 120,
    packaging_date: moment().subtract(15, "days").toDate(),
    expiry_date: moment().add(6, "months").toDate(),
    description: "Premium aged Basmati rice with long grains.",
    extra_note: "Store in a dry place.",
  },
  {
    name: "Wheat Flour 10kg",
    brand: "Aashirvaad",
    category_id: 2,
    SKU: "SKU002",
    weight: 10,
    weight_unit: WeightUnits.Kg,
    MRP: 400.0,
    available_quantity: 70,
    sold_quantity: 250,
    packaging_date: moment().subtract(20, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description: "Whole wheat chakki atta for soft rotis.",
    extra_note: "",
  },
  {
    name: "Besan (Gram Flour) 1kg",
    brand: "Fortune",
    category_id: 3,
    SKU: "SKU003",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 85.0,
    available_quantity: 100,
    sold_quantity: 80,
    packaging_date: moment().subtract(10, "days").toDate(),
    expiry_date: moment().add(3, "months").toDate(),
    description: "Fine quality besan for cooking and sweets.",
    extra_note: "",
  },
  {
    name: "Maida 1kg",
    brand: "Pillsbury",
    category_id: 4,
    SKU: "SKU004",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 60.0,
    available_quantity: 40,
    sold_quantity: 50,
    packaging_date: moment().subtract(5, "days").toDate(),
    expiry_date: moment().add(2, "months").toDate(),
    description: "Refined flour ideal for baking and frying.",
    extra_note: "",
  },
  {
    name: "Multigrain Atta 5kg",
    brand: "Aashirvaad",
    category_id: 2,
    SKU: "SKU005",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 320.0,
    available_quantity: 35,
    sold_quantity: 60,
    packaging_date: moment().subtract(18, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description: "Blend of 6 grains for healthier rotis.",
    extra_note: "Good for diabetic diet.",
  },
  {
    name: "Brown Rice 5kg",
    brand: "Daawat",
    category_id: 1,
    SKU: "SKU006",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 450.0,
    available_quantity: 20,
    sold_quantity: 90,
    packaging_date: moment().subtract(12, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description: "Healthy brown rice rich in fiber.",
    extra_note: "",
  },
  {
    name: "Sooji (Rava) 1kg",
    brand: "Patanjali",
    category_id: 4,
    SKU: "SKU007",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 40.0,
    available_quantity: 100,
    sold_quantity: 70,
    packaging_date: moment().subtract(7, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description: "Fine semolina for upma and halwa.",
    extra_note: "",
  },
  {
    name: "Wheat Flour 5kg",
    brand: "Patanjali",
    category_id: 2,
    SKU: "SKU008",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 200.0,
    available_quantity: 60,
    sold_quantity: 100,
    packaging_date: moment().subtract(10, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description: "Stone-ground wheat atta.",
    extra_note: "",
  },
  {
    name: "Organic Basmati Rice 1kg",
    brand: "24 Mantra",
    category_id: 1,
    SKU: "SKU009",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 130.0,
    available_quantity: 80,
    sold_quantity: 40,
    packaging_date: moment().subtract(25, "days").toDate(),
    expiry_date: moment().add(6, "months").toDate(),
    description: "Certified organic long-grain basmati rice.",
    extra_note: "No preservatives.",
  },
  {
    name: "Besan 500g",
    brand: "Catch",
    category_id: 3,
    SKU: "SKU010",
    weight: 500,
    weight_unit: WeightUnits.Gram,
    MRP: 50.0,
    available_quantity: 90,
    sold_quantity: 70,
    packaging_date: moment().subtract(14, "days").toDate(),
    expiry_date: moment().add(3, "months").toDate(),
    description: "High protein gram flour.",
    extra_note: "",
  },
  {
    name: "Wheat Dalia 500g",
    brand: "Natureland",
    category_id: 2,
    SKU: "SKU011",
    weight: 500,
    weight_unit: WeightUnits.Gram,
    MRP: 40.0,
    available_quantity: 45,
    sold_quantity: 30,
    packaging_date: moment().subtract(9, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description: "Cracked wheat perfect for porridge.",
    extra_note: "",
  },
  {
    name: "Maida 500g",
    brand: "Catch",
    category_id: 4,
    SKU: "SKU012",
    weight: 500,
    weight_unit: WeightUnits.Gram,
    MRP: 30.0,
    available_quantity: 50,
    sold_quantity: 20,
    packaging_date: moment().subtract(6, "days").toDate(),
    expiry_date: moment().add(2, "months").toDate(),
    description: "Refined flour for parathas & snacks.",
    extra_note: "",
  },
  {
    name: "Brown Rice 1kg",
    brand: "Natureland",
    category_id: 1,
    SKU: "SKU013",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 90.0,
    available_quantity: 70,
    sold_quantity: 45,
    packaging_date: moment().subtract(8, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description: "Unpolished brown rice for health-conscious diet.",
    extra_note: "",
  },
  {
    name: "Wheat Flour 2kg",
    brand: "24 Mantra Organic",
    category_id: 2,
    SKU: "SKU014",
    weight: 2,
    weight_unit: WeightUnits.Kg,
    MRP: 110.0,
    available_quantity: 30,
    sold_quantity: 60,
    packaging_date: moment().subtract(5, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description: "Organic whole wheat flour.",
    extra_note: "Certified organic",
  },
  {
    name: "Multigrain Atta 1kg",
    brand: "Fortune",
    category_id: 2,
    SKU: "SKU015",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 75.0,
    available_quantity: 25,
    sold_quantity: 55,
    packaging_date: moment().subtract(10, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description: "A wholesome blend of grains for daily health.",
    extra_note: "",
  },
];

export const productImagesData = [
  {
    product_id: 1,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 1,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 2,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 2,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 3,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 3,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 4,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 4,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 5,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 5,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 6,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 6,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 7,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 7,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 8,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 8,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 9,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 9,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 10,
    image_url: "./images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 10,
    image_url: "./images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
];
