import { WeightUnits } from "@/database/models/types/products.type";
import moment from "moment";

export const categoryData = [
  {
    name: "Rice",
  },
  {
    name: "Wheat",
  },
  {
    name: "Besan",
  },
  {
    name: "Maida",
  },
  {
    name: "Others",
  },
];

export const productsData = [
  {
    name: "Basmati Rice 5kg",
    brand: "India Gate",
    category_id: 1,
    SKU: "SKU001",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 580.0,
    available_quantity: 50,
    sold_quantity: 120,
    packaging_date: moment().subtract(15, "days").toDate(),
    expiry_date: moment().add(6, "months").toDate(),
    description:
      "India Gate Basmati Rice is premium-quality long-grain rice that has been aged for superior flavor and texture. Known for its distinct aroma and fluffy texture, it's ideal for biryanis, pulaos, and special occasions. Grown in the fertile lands of the Himalayas, this rice is naturally nutritious and easy to digest.",
    extra_note: "Store in a dry place.",
    discount: 10,
    selling_price: 522.0,
  },
  {
    name: "Wheat Flour 10kg",
    brand: "Aashirvaad",
    category_id: 2,
    SKU: "SKU002",
    weight: 10,
    weight_unit: WeightUnits.Kg,
    MRP: 400.0,
    available_quantity: 70,
    sold_quantity: 250,
    packaging_date: moment().subtract(20, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description:
      "Aashirvaad Whole Wheat Atta is made from the choicest grains, grounded using traditional chakki grinding techniques. It retains the natural goodness of wheat, ensuring soft, fluffy rotis every time. Fortified with essential nutrients, this flour promotes better digestion and overall wellness.",
    extra_note: "",
    discount: 5,
    selling_price: 380.0,
  },
  {
    name: "Besan (Gram Flour) 1kg",
    brand: "Fortune",
    category_id: 3,
    SKU: "SKU003",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 85.0,
    available_quantity: 100,
    sold_quantity: 80,
    packaging_date: moment().subtract(10, "days").toDate(),
    expiry_date: moment().add(3, "months").toDate(),
    description:
      "Fortune Besan is made from the finest quality chana dal, ground to perfection to ensure a smooth and consistent texture. Ideal for preparing savory snacks, sweets, and batters, it’s a protein-rich, gluten-free flour that brings authentic taste to every dish.",
    extra_note: "",
    discount: 0,
    selling_price: 85.0,
  },
  {
    name: "Maida 1kg",
    brand: "Pillsbury",
    category_id: 4,
    SKU: "SKU004",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 60.0,
    available_quantity: 40,
    sold_quantity: 50,
    packaging_date: moment().subtract(5, "days").toDate(),
    expiry_date: moment().add(2, "months").toDate(),
    description:
      "Pillsbury Maida is finely refined all-purpose flour, perfect for preparing soft bhaturas, crispy puris, delicious baked goods, and a variety of Indian and Western snacks. It is processed with precision to retain the white color and fine texture.",
    extra_note: "",
    discount: 5,
    selling_price: 57.0,
  },
  {
    name: "Multigrain Atta 5kg",
    brand: "Aashirvaad",
    category_id: 2,
    SKU: "SKU005",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 320.0,
    available_quantity: 35,
    sold_quantity: 60,
    packaging_date: moment().subtract(18, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description:
      "Aashirvaad Multigrain Atta is a health-focused flour blend made with six nutritious grains – wheat, soya, channa, oats, maize, and psyllium husk. Rich in dietary fiber and essential nutrients, it helps manage weight, sugar levels, and digestion, making it ideal for a balanced diet.",
    extra_note: "Good for diabetic diet.",
    discount: 0,
    selling_price: 320.0,
  },
  {
    name: "Brown Rice 5kg",
    brand: "Daawat",
    category_id: 1,
    SKU: "SKU006",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 450.0,
    available_quantity: 20,
    sold_quantity: 90,
    packaging_date: moment().subtract(12, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description:
      "Daawat Brown Rice is a wholesome and fiber-rich alternative to regular white rice. Retaining the nutritious bran layer, it supports better digestion, improved heart health, and aids in weight management. Great for daily meals, salads, and health bowls.",
    extra_note: "",
    discount: 7,
    selling_price: 418.5,
  },
  {
    name: "Sooji (Rava) 1kg",
    brand: "Patanjali",
    category_id: 4,
    SKU: "SKU007",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 65.0,
    available_quantity: 100,
    sold_quantity: 70,
    packaging_date: moment().subtract(7, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description:
      "Patanjali Sooji is high-quality semolina made from hard wheat. It is perfect for preparing Indian delicacies like upma, halwa, idlis, and dhokla. Easy to digest and naturally nutritious, it is a must-have ingredient in every kitchen.",
    extra_note: "",
    discount: 20,
    selling_price: 52.0,
  },
  {
    name: "Wheat Flour 5kg",
    brand: "Patanjali",
    category_id: 2,
    SKU: "SKU008",
    weight: 5,
    weight_unit: WeightUnits.Kg,
    MRP: 200.0,
    available_quantity: 60,
    sold_quantity: 100,
    packaging_date: moment().subtract(10, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description:
      "Patanjali Whole Wheat Atta is stone-ground using traditional methods to preserve nutrients and texture. Made from select grains, it ensures soft and delicious rotis, offering a natural source of energy and essential fiber.",
    extra_note: "",
    discount: 5,
    selling_price: 190.0,
  },
  {
    name: "Organic Basmati Rice 1kg",
    brand: "24 Mantra",
    category_id: 1,
    SKU: "SKU009",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 130.0,
    available_quantity: 80,
    sold_quantity: 40,
    packaging_date: moment().subtract(25, "days").toDate(),
    expiry_date: moment().add(6, "months").toDate(),
    description:
      "24 Mantra Organic Basmati Rice is grown without the use of synthetic pesticides or fertilizers. With its long, slender grains and distinct aroma, it is perfect for daily meals and special dishes. This rice supports organic farming and a healthy lifestyle.",
    extra_note: "No preservatives.",
    discount: 10,
    selling_price: 117.0,
  },
  {
    name: "Besan 500g",
    brand: "Catch",
    category_id: 3,
    SKU: "SKU010",
    weight: 500,
    weight_unit: WeightUnits.Gram,
    MRP: 75.0,
    available_quantity: 90,
    sold_quantity: 70,
    packaging_date: moment().subtract(14, "days").toDate(),
    expiry_date: moment().add(3, "months").toDate(),
    description:
      "Catch Besan is finely milled from high-quality chana dal. Rich in protein and fiber, it is used in traditional Indian dishes like pakoras, kadhi, and sweets. It’s naturally gluten-free and helps support vegetarian diets with vital nutrients.",
    extra_note: "",
    discount: 30,
    selling_price: 52.5,
  },
  {
    name: "Wheat Dalia 500g",
    brand: "Natureland",
    category_id: 2,
    SKU: "SKU011",
    weight: 500,
    weight_unit: WeightUnits.Gram,
    MRP: 72.0,
    available_quantity: 45,
    sold_quantity: 30,
    packaging_date: moment().subtract(9, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description:
      "Natureland Wheat Dalia is made from 100% whole wheat and is rich in fiber and complex carbohydrates. It is ideal for preparing nutritious porridge, upma, or khichdi, and is known to aid digestion and regulate blood sugar levels.",
    extra_note: "",
    discount: 25,
    selling_price: 54.0,
  },
  {
    name: "Maida 500g",
    brand: "Catch",
    category_id: 4,
    SKU: "SKU012",
    weight: 500,
    weight_unit: WeightUnits.Gram,
    MRP: 68.0,
    available_quantity: 50,
    sold_quantity: 20,
    packaging_date: moment().subtract(6, "days").toDate(),
    expiry_date: moment().add(2, "months").toDate(),
    description:
      "Catch Maida is premium refined flour suitable for baking cakes, making naans, puris, samosas, and other delicious treats. It is finely milled and bleached to maintain whiteness and softness for culinary versatility.",
    extra_note: "",
    discount: 22,
    selling_price: 53.04,
  },
  {
    name: "Brown Rice 1kg",
    brand: "Natureland",
    category_id: 1,
    SKU: "SKU013",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 90.0,
    available_quantity: 70,
    sold_quantity: 45,
    packaging_date: moment().subtract(8, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description:
      "Natureland Brown Rice is unpolished and retains the bran layer, which is rich in fiber and antioxidants. It is a healthy alternative to white rice, ideal for people managing weight, cholesterol, or diabetes. Delicious in salads, curries, and pilafs.",
    extra_note: "",
    discount: 8,
    selling_price: 82.8,
  },
  {
    name: "Wheat Flour 2kg",
    brand: "24 Mantra Organic",
    category_id: 2,
    SKU: "SKU014",
    weight: 2,
    weight_unit: WeightUnits.Kg,
    MRP: 110.0,
    available_quantity: 30,
    sold_quantity: 60,
    packaging_date: moment().subtract(5, "days").toDate(),
    expiry_date: moment().add(4, "months").toDate(),
    description:
      "24 Mantra Organic Wheat Flour is made from organically grown wheat, free from chemicals and preservatives. It is rich in fiber and nutrients, perfect for making rotis and parathas. A great choice for health-conscious families.",
    extra_note: "Certified organic",
    discount: 5,
    selling_price: 104.5,
  },
  {
    name: "Multigrain Atta 1kg",
    brand: "Fortune",
    category_id: 2,
    SKU: "SKU015",
    weight: 1,
    weight_unit: WeightUnits.Kg,
    MRP: 75.0,
    available_quantity: 25,
    sold_quantity: 55,
    packaging_date: moment().subtract(10, "days").toDate(),
    expiry_date: moment().add(5, "months").toDate(),
    description:
      "Fortune Multigrain Atta is made with a blend of wheat, oats, maize, soya, and barley, offering a rich source of fiber and essential nutrients. It helps in digestion, weight control, and boosts energy levels while delivering the taste of homemade rotis.",
    extra_note: "",
    discount: 0,
    selling_price: 75.0,
  },
];

export const productImagesData = [
  {
    product_id: 1,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 1,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 2,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 2,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 3,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 3,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 4,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 4,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 5,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 5,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 6,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 6,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 7,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 7,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 8,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 8,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 9,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 9,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
  {
    product_id: 10,
    image_url: "/images/test-product-front.png",
    alt_name: "Front Picture",
    is_primary: true,
  },
  {
    product_id: 10,
    image_url: "/images/test-product-back.png",
    alt_name: "Back Picture",
    is_secondary: true,
  },
];

export const productReviewsData = [
  {
    product_id: 1,
    rating: 4.25,
    review: "Great Product",
  },
  {
    product_id: 2,
    rating: 4.5,
    review: "Amazing Product",
  },
  {
    product_id: 3,
    rating: 3,
    review: "Decent Product",
  },
  {
    product_id: 4,
    rating: 5,
    review: "Best Product",
  },
  {
    product_id: 5,
    rating: 4.25,
    review: "Great Product",
  },
  {
    product_id: 6,
    rating: 2,
    review: "Not that good",
  },
  {
    product_id: 7,
    rating: 4,
    review: "Great value for money",
  },
  {
    product_id: 8,
    rating: 4.25,
    review: "Great Product",
  },
];
